/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package afs.student.ui;
import javax.swing.JOptionPane;
import afs.student.service.StudentService;
import afs.student.model.Student;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ideapad
 */
public class StudentDashboardFrame extends javax.swing.JFrame {

    
    private Student currentStudent;

    /**
     * Creates new form StudentDashboardFrame
     */
    public StudentDashboardFrame() {
        initComponents();
    }
    
    public StudentDashboardFrame(Student student) {
    initComponents();
    this.currentStudent = student;
    
    

    txtName.setText(student.getName());
    txtStudentId.setText(student.getStudentId());
    txtEmail.setText(student.getEmail());
    txtPhone.setText(student.getPhone());
    txtAge.setText(String.valueOf(student.getAge()));
    txtIntake.setText(student.getIntakeCode());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlProfile = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblIntakeCode = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtStudentId = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtIntake = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        pnlRegister = new javax.swing.JPanel();
        lblRegStudentId = new javax.swing.JLabel();
        lblRegPassword = new javax.swing.JLabel();
        lblRegConfirm = new javax.swing.JLabel();
        txtRegStudentId = new javax.swing.JTextField();
        txtRegPassword = new javax.swing.JTextField();
        txtRegConfirm = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        pnlResults = new javax.swing.JPanel();
        pnlResultsTop = new javax.swing.JPanel();
        btnRefreshResults = new javax.swing.JButton();
        lblResultsStatus = new javax.swing.JLabel();
        spResults = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();
        pnlComments = new javax.swing.JPanel();
        pnlCommentsTop = new javax.swing.JPanel();
        lblModule = new javax.swing.JLabel();
        cmbCommentModule = new javax.swing.JComboBox<>();
        btnSendComment = new javax.swing.JButton();
        pnlCommentsBody = new javax.swing.JPanel();
        lblWriteComment = new javax.swing.JLabel();
        spWriteComment = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        spComments = new javax.swing.JScrollPane();
        tblComments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(480, 650));

        lblFullName.setText("Name :\n");
        lblFullName.setPreferredSize(new java.awt.Dimension(90, 25));

        lblStudentId.setText("Student ID :");
        lblStudentId.setPreferredSize(new java.awt.Dimension(90, 25));

        lblEmail.setText("Email :");
        lblEmail.setPreferredSize(new java.awt.Dimension(90, 25));

        lblPhone.setText("Phone :");
        lblPhone.setPreferredSize(new java.awt.Dimension(90, 25));

        lblGender.setText("Gender :");
        lblGender.setPreferredSize(new java.awt.Dimension(90, 25));

        lblAge.setText("Age :");
        lblAge.setPreferredSize(new java.awt.Dimension(90, 25));

        lblIntakeCode.setText("Intake : ");
        lblIntakeCode.setPreferredSize(new java.awt.Dimension(90, 25));

        txtName.setPreferredSize(new java.awt.Dimension(260, 25));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtStudentId.setPreferredSize(new java.awt.Dimension(260, 25));

        txtEmail.setPreferredSize(new java.awt.Dimension(260, 25));

        txtPhone.setPreferredSize(new java.awt.Dimension(260, 25));

        txtAge.setPreferredSize(new java.awt.Dimension(60, 28));

        txtIntake.setPreferredSize(new java.awt.Dimension(260, 25));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female" }));
        cmbGender.setPreferredSize(new java.awt.Dimension(140, 28));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIntakeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIntake, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addGap(131, 131, 131))
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProfileLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmail, txtIntake, txtName, txtPhone, txtStudentId});

        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntakeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSave)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pnlProfileLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmail, txtIntake, txtName, txtPhone, txtStudentId});

        jTabbedPane1.addTab("Profile", pnlProfile);

        lblRegStudentId.setText("Student ID :");
        lblRegStudentId.setPreferredSize(new java.awt.Dimension(110, 18));

        lblRegPassword.setText("Password :");
        lblRegPassword.setPreferredSize(new java.awt.Dimension(110, 18));

        lblRegConfirm.setText("Confirm Password :");
        lblRegConfirm.setPreferredSize(new java.awt.Dimension(110, 18));

        txtRegStudentId.setPreferredSize(new java.awt.Dimension(260, 28));

        txtRegPassword.setPreferredSize(new java.awt.Dimension(260, 28));

        txtRegConfirm.setPreferredSize(new java.awt.Dimension(260, 28));

        btnRegister.setText("Register");
        btnRegister.setPreferredSize(new java.awt.Dimension(110, 32));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRegStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegStudentId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register", pnlRegister);

        pnlResultsTop.setName(""); // NOI18N

        btnRefreshResults.setText("Refresh");
        btnRefreshResults.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRefreshResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshResultsActionPerformed(evt);
            }
        });

        lblResultsStatus.setText("Status");
        lblResultsStatus.setPreferredSize(new java.awt.Dimension(250, 25));

        javax.swing.GroupLayout pnlResultsTopLayout = new javax.swing.GroupLayout(pnlResultsTop);
        pnlResultsTop.setLayout(pnlResultsTopLayout);
        pnlResultsTopLayout.setHorizontalGroup(
            pnlResultsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsTopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnRefreshResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblResultsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResultsTopLayout.setVerticalGroup(
            pnlResultsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshResults, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Assessment", "Type", "Total Marks", "Weightage", "Marks", "Grade", "Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spResults.setViewportView(tblResults);

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addComponent(pnlResultsTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(spResults, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)))
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addComponent(pnlResultsTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spResults, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Results", pnlResults);

        pnlComments.setPreferredSize(new java.awt.Dimension(480, 420));

        pnlCommentsTop.setPreferredSize(new java.awt.Dimension(480, 60));

        lblModule.setText("Module");
        lblModule.setPreferredSize(new java.awt.Dimension(60, 25));

        cmbCommentModule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCommentModule.setPreferredSize(new java.awt.Dimension(260, 28));
        cmbCommentModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCommentModuleActionPerformed(evt);
            }
        });

        btnSendComment.setText("Send");
        btnSendComment.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSendComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCommentsTopLayout = new javax.swing.GroupLayout(pnlCommentsTop);
        pnlCommentsTop.setLayout(pnlCommentsTopLayout);
        pnlCommentsTopLayout.setHorizontalGroup(
            pnlCommentsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCommentsTopLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblModule, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCommentModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSendComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlCommentsTopLayout.setVerticalGroup(
            pnlCommentsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCommentsTopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlCommentsTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCommentModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlCommentsBody.setPreferredSize(new java.awt.Dimension(440, 420));

        lblWriteComment.setText("Write your comment");
        lblWriteComment.setPreferredSize(new java.awt.Dimension(150, 25));

        txtComment.setColumns(20);
        txtComment.setLineWrap(true);
        txtComment.setRows(8);
        txtComment.setWrapStyleWord(true);
        spWriteComment.setViewportView(txtComment);

        tblComments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student", "Comment", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spComments.setViewportView(tblComments);

        javax.swing.GroupLayout pnlCommentsBodyLayout = new javax.swing.GroupLayout(pnlCommentsBody);
        pnlCommentsBody.setLayout(pnlCommentsBodyLayout);
        pnlCommentsBodyLayout.setHorizontalGroup(
            pnlCommentsBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCommentsBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCommentsBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCommentsBodyLayout.createSequentialGroup()
                        .addComponent(lblWriteComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCommentsBodyLayout.createSequentialGroup()
                        .addComponent(spWriteComment, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spComments, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlCommentsBodyLayout.setVerticalGroup(
            pnlCommentsBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCommentsBodyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblWriteComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCommentsBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spComments, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(spWriteComment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCommentsLayout = new javax.swing.GroupLayout(pnlComments);
        pnlComments.setLayout(pnlCommentsLayout);
        pnlCommentsLayout.setHorizontalGroup(
            pnlCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCommentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCommentsTop, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(pnlCommentsBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)))
        );
        pnlCommentsLayout.setVerticalGroup(
            pnlCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCommentsLayout.createSequentialGroup()
                .addComponent(pnlCommentsTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCommentsBody, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comments", pnlComments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
 String id = txtRegStudentId.getText().trim();
    String pass = txtRegPassword.getText().trim();
    String confirm = txtRegConfirm.getText().trim();

    if (id.isEmpty() || pass.isEmpty() || confirm.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    if (!pass.equals(confirm)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match.");
        return;
    }

    try {
        boolean ok = new StudentService().register(id, pass);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Registered successfully!");
            txtRegStudentId.setText("");
            txtRegPassword.setText("");
            txtRegConfirm.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Student ID already exists.");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRefreshResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshResultsActionPerformed
try {
    StudentService service = new StudentService();

        java.util.List<StudentService.ResultRow> rows =
                service.myResults(currentStudent.getStudentId());

        DefaultTableModel model = (DefaultTableModel) tblResults.getModel();
        model.setRowCount(0);

        for (StudentService.ResultRow r : rows) {
            model.addRow(new Object[]{
                r.assessmentName,
                r.type,
                r.totalMarks,
                r.weightage,
                r.marks,
                r.grade,
                r.feedbackText
            });
        }

        lblResultsStatus.setText("Status: Loaded " + rows.size() + " result(s)");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Error: " + ex.getMessage(),
                "Results",
                JOptionPane.ERROR_MESSAGE);
        lblResultsStatus.setText("Status: Error"); 
}
    }//GEN-LAST:event_btnRefreshResultsActionPerformed

    private void cmbCommentModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCommentModuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCommentModuleActionPerformed

    private void btnSendCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendCommentActionPerformed

 try {
      String comment = txtComment.getText().trim();

        if (comment.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please write a comment first.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblComments.getModel();

        String studentName = (currentStudent != null && currentStudent.getName() != null && !currentStudent.getName().isBlank())
                ? currentStudent.getName()
                : "Me";

        String date = java.time.LocalDate.now().toString();

        model.addRow(new Object[]{ studentName, comment, date });

        txtComment.setText("");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
       
    }//GEN-LAST:event_btnSendCommentActionPerformed
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
 try {
        String name   = txtName.getText().trim();
        String email  = txtEmail.getText().trim();
        String phone  = txtPhone.getText().trim();
        String gender = (cmbGender.getSelectedItem() == null) ? "" : cmbGender.getSelectedItem().toString().trim();
        String ageStr = txtAge.getText().trim();

        String newPassword = askNewPassword();
        if (newPassword == null) return;

        if (currentStudent == null) {
            JOptionPane.showMessageDialog(this, "No student is logged in.", "Profile", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StudentService service = new StudentService();
        service.updateProfile(currentStudent, newPassword, name, gender, email, phone, ageStr);

        JOptionPane.showMessageDialog(this, "Profile saved successfully.", "Profile", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Profile", JOptionPane.ERROR_MESSAGE);
    }
}

private String askNewPassword() {
    javax.swing.JPasswordField pf = new javax.swing.JPasswordField();
    int ok = JOptionPane.showConfirmDialog(
            this,
            pf,
            "Enter new password",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
    );
    if (ok != JOptionPane.OK_OPTION) return null;

    String pass = new String(pf.getPassword()).trim();
    if (pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password is required.", "Profile", JOptionPane.ERROR_MESSAGE);
        return null;
    }
    return pass;
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshResults;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSendComment;
    private javax.swing.JComboBox<String> cmbCommentModule;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIntakeCode;
    private javax.swing.JLabel lblModule;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRegConfirm;
    private javax.swing.JLabel lblRegPassword;
    private javax.swing.JLabel lblRegStudentId;
    private javax.swing.JLabel lblResultsStatus;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblWriteComment;
    private javax.swing.JPanel pnlComments;
    private javax.swing.JPanel pnlCommentsBody;
    private javax.swing.JPanel pnlCommentsTop;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JPanel pnlResultsTop;
    private javax.swing.JScrollPane spComments;
    private javax.swing.JScrollPane spResults;
    private javax.swing.JScrollPane spWriteComment;
    private javax.swing.JTable tblComments;
    private javax.swing.JTable tblResults;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIntake;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRegConfirm;
    private javax.swing.JTextField txtRegPassword;
    private javax.swing.JTextField txtRegStudentId;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
